# Generated by Django 3.0.3 on 2020-03-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_authorasslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='answer_to',
            new_name='answerTo',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='notification',
            new_name='notifications',
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='notes.Tag'),
        ),
    ]
